### ISSUE TITLE
input_4hourly and max_dose_vaso : should they be part of the next step's observation ?

### ISSUE THREAD

**Issue by pathway** [microsoft/mimic_sepsis#12]
I am just seeking clarification.

Im looking at sepsis_final_data_withTimes.csv and sepsis_cohort.py

If I understand correctly, action is derived from input_4hourly and max_dose_vaso.  We can say the action decision causes input_4hourly and max_dose_vaso, not the other way round.

Therefore input_4hourly and max_dose_vaso must not be considered part of the observation for the current step, but perhaps for the next step.

Is this correct?

In that case I may want to shift these two columns one step forward in time, to allow them to be used in observations.

**Comment by fatemi** [comment]
Hi @pathway
This code closely follows the AI Clinician's MATLAB code, cited in the readme. You are right about the actions. For RL implementations you need to remove the corresponding columns from the observations, even though AI Clinician wrongly uses them. We may remove them from the cohort generator to avoid confusions (though keeping them as a reference for raw inputs might also be helpful).

**Comment by twkillian** [comment]
I want to quickly chime in here and say that the suggested fix that @pathway cited (of shifting the features corresponding to the fluids and vasopressors one time step forward so that the features would correspond to the previous action) is not a bad way to still use these columns. In that way, you form an approximate or psuedo belief state.

**Comment by fatemi** [comment]
These are raw observations. As for the previous actions, I'd append them at the RL level not here. That way, online models can have a transparent implementation with the same interface for learning as well as run-time. Having said that, these columns might still be helpful (e.g., for continuous actions), so I tend to keep them, but perhaps with a different prefix.

**Comment by pathway** [comment]
Thank you both for your helpful comments!  Glad to see my finding is not a surprise, and yes I will either remove or shift these cols for my purposes.

I am deeply grateful to you for this repo, I can see it represents much painstaking work, and is an incredible resource for the community.
