### ISSUE TITLE
Extracting Text Notes for Sepsis Data

### ISSUE THREAD

**Issue by ayubih** [microsoft/mimic_sepsis#17]
I wanted to ask if there is a separate code for identifying the sepsis criteria in the dataset or just adding a column for all the textual information for each instance here when creating the sepsis dataset. I wanted to test with clinical notes for classification of sepsis in the final data.

**Comment by twkillian** [comment]
Hi, thanks for asking. We use the clinical Sepsis3 criteria to define Sepsis, which is done pretty early on in the `sepsis_cohort.py` script (https://github.com/microsoft/mimic_sepsis/blob/main/sepsis_cohort.py#L250-L283). 

I think that it's a great idea to cross-reference with the clinical notes. It should be pretty straightforward to use the filtered `icustayid`s that are presumed to have Sepsis and then cross-reference with the `charttimes` under consideration to extract the notes.

**Comment by hsuyab** [comment]
- So the lines 250-283 are the sepsis3 criteria? 
- I already have created the sepsis_cohorts by running this file. In the final files, I am getting a `traj` and `step` columns without any identifiers to map with the notes. So, the `charttimes` would help me map with extracted notes in here?

**Comment by ayubih** [comment]
In case of data collected for the Metavision system, in the `INPUTEVENTS_MV.csv.gz` there is no `charttimes` that has been given then  can you tell how to cross-reference the data there to extract the notes. I was able to do it for the data for the CareVue system.

**Comment by twkillian** [comment]
All input events have a `starttime` and `endtime` columns, correct? You can make a determination on how to select the timing for cross referencing with the notes.

**Comment by ayubih** [comment]
Are you suggesting that based on the `starttime` and `endtime` we look at whatever the in between `charttimes` (for a particular `ICUSTAY_ID`) are and then decide on the notes.

**Comment by twkillian** [comment]
Yes, I'm going to consider this issue as closed as I trust you have the facility to determine the best path forward for the remainder of your work.

**Comment by twkillian** [comment]
@fatemi, are you able to close this issue?

**Comment by fatemi** [comment]
@twkillian No. Someone from MS should do it.
