### ISSUE TITLE
RuntimeError numpy

### ISSUE THREAD

**Issue by antranttu** [microsoft/mimic_sepsis#6]
Hello,

When running the "sepsis_cohort.py", I got:

`RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd`

even though I installed the same versions of the packages in `requirements.txt`. Do you have any idea what the error was about?

Thank you.

**Comment by fatemi** [comment]
Try to update your numpy by `conda update numpy`  OR  `pip install numpy --upgrade`. The code here should work with latest version of numpy.
